const quizData = [
  {
    "id": 1,
    "part": 1,
    "question": "",
    "audio": "sounds/1-01.mp3",
    "image": "images/01.png",
    "transcript": "提問 請問這裡是哪裡？\n(A) 教堂\n(B) 學校\n(C) 博物館",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 2,
    "part": 1,
    "question": "",
    "audio": "sounds/1-02.mp3",
    "image": "images/02.png",
    "transcript": "提問 請問這是什麼動物？\n(A) 一隻鳥\n(B) 一隻雞\n(C) 一匹馬",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 3,
    "part": 1,
    "question": "",
    "audio": "sounds/1-03.mp3",
    "image": "images/03.png",
    "transcript": "提問 請問這是什麼地方？\n(A) 工廠\n(B) 公園\n(C) 車站",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 4,
    "part": 1,
    "question": "",
    "audio": "sounds/1-04.mp3",
    "image": "images/04.png",
    "transcript": "提問 請問這個人怎麼了？\n(A) 他的耳朵很痛\n(B) 他的肚子不舒服\n(C) 他的手指頭受傷了",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 5,
    "part": 1,
    "question": "",
    "audio": "sounds/1-05.mp3",
    "image": "images/05.png",
    "transcript": "提問 請問他們在玩什麼？\n(A) 足球\n(B) 棒球\n(C) 網球",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 6,
    "part": 1,
    "question": "",
    "audio": "sounds/1-06.mp3",
    "image": "images/06.png",
    "transcript": "提問 請問王先生的職業是什麼？\n(A) 教師\n(B) 經理\n(C) 記者",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 7,
    "part": 1,
    "question": "",
    "audio": "sounds/1-07.mp3",
    "image": "images/07.png",
    "transcript": "提問 請問這裡的天氣怎麼樣？\n(A) 沒有太陽\n(B) 正在下雨\n(C) 有一點熱",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 8,
    "part": 1,
    "question": "",
    "audio": "sounds/1-08.mp3",
    "image": "images/08.png",
    "transcript": "提問 桌子上有什麼？\n(A) 只有信封和燈\n(B) 有燈也有卡片\n(C) 有信封沒有卡片",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 9,
    "part": 1,
    "question": "",
    "audio": "sounds/1-09.mp3",
    "image": "images/09.png",
    "transcript": "提問 圖片裡的人準備做什麼？\n(A) 他們準備坐車。\n(B) 他們準備騎車。\n(C) 他們準備買車票。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 10,
    "part": 1,
    "question": "",
    "audio": "sounds/1-10.mp3",
    "image": "images/10.png",
    "transcript": "提問 請問王小姐正在做什麼？\n(A) 她正在收傳真\n(B) 她正在打電腦\n(C) 她正在寫卡片",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 11,
    "part": 2,
    "question": "",
    "audio": "sounds/2-11.mp3",
    "image": "images/11.png",
    "transcript": "男 請問還要點菜嗎？\n女 不用了，我吃飽了，麻煩算算一共多少錢。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 12,
    "part": 2,
    "question": "",
    "audio": "sounds/2-12.mp3",
    "image": "images/12.png",
    "transcript": "男 小華，妳放假的時候都做什麼？\n女 我常常去游泳。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 13,
    "part": 2,
    "question": "",
    "audio": "sounds/2-13.mp3",
    "image": "images/13.png",
    "transcript": "男 你怎麼有這本書？\n女 我爸爸送我的。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 14,
    "part": 2,
    "question": "",
    "audio": "sounds/2-14.mp3",
    "image": "images/14.png",
    "transcript": "男 麗美，妳怎麼來了？\n女 昨天買的衣服想換不同的顏色。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 15,
    "part": 2,
    "question": "",
    "audio": "sounds/2-15.mp3",
    "image": "images/15.png",
    "transcript": "男 你想喝什麼？茶還是咖啡？\n女 我想喝啤酒。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 16,
    "part": 2,
    "question": "",
    "audio": "sounds/2-16.mp3",
    "image": "images/16.png",
    "transcript": "男 請問去動物園怎麼走？\n女 你往前走，然後在第二個路口左轉，你就會看到動物園了。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 17,
    "part": 2,
    "question": "",
    "audio": "sounds/2-17.mp3",
    "image": "images/17.png",
    "transcript": "男 你記得你最後一次是在哪裡看見錢包的嗎？\n女 警察先生，我記得應該是買東西的時候。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 18,
    "part": 2,
    "question": "",
    "audio": "sounds/2-18.mp3",
    "image": "images/18.png",
    "transcript": "男 醫生，我這次要去森林裡住一個月，請問有什麼要注意的事？\n女 你要帶一些藥，嗯～一定要喝開水，這個要記得。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 19,
    "part": 2,
    "question": "",
    "audio": "sounds/2-19.mp3",
    "image": "images/19.png",
    "transcript": "男 美美，你看見我的字典了嗎？\n女 你拿去臥室了。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 20,
    "part": 2,
    "question": "",
    "audio": "sounds/2-20.mp3",
    "image": "images/20.png",
    "transcript": "男 我會煮飯和掃地，請問我可以住在這裡嗎？\n女 我不需要工人，你想住在這裡就付房租，一天三百元。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 21,
    "part": 2,
    "question": "",
    "audio": "sounds/2-21.mp3",
    "image": "images/21.png",
    "transcript": "男 我昨天打電話給你，你怎麼沒接電話？\n女 我的手機壞了。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 22,
    "part": 2,
    "question": "",
    "audio": "sounds/2-22.mp3",
    "image": "images/22.png",
    "transcript": "男 你了解我要你做什麼事情了嗎？\n女 我…我還是不懂。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 23,
    "part": 2,
    "question": "",
    "audio": "sounds/2-23.mp3",
    "image": "images/23.png",
    "transcript": "男 這家店為什麼這麼多人在排隊？\n女 因為這裡的衣服很便宜，很多人來這裡買衣服。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 24,
    "part": 2,
    "question": "",
    "audio": "sounds/2-24.mp3",
    "image": "images/24.png",
    "transcript": "男 現在天氣怎麼樣？\n女 很涼快、很舒服，我想出去走走。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 25,
    "part": 2,
    "question": "",
    "audio": "sounds/2-25.mp3",
    "image": "images/25.png",
    "transcript": "男 妳剛剛打電話給我，有什麼事嗎？\n女 家裡的洗衣機和冰箱都壞了。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 26,
    "part": 3,
    "question": "",
    "audio": "sounds/3-26.mp3",
    "image": "images/26.png",
    "transcript": "男 怎麼最近都沒看到陳老師呢？\n女 聽說陳老師生病了，現在在醫院裡。\n男 我們應該去醫院看看他，我們帶水果和花去看他，好不好？\n女 陳老師很喜歡看書，我想買幾本有趣的書給他。\n男 請問這位小姐想帶什麼東西給陳老師？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 27,
    "part": 3,
    "question": "",
    "audio": "sounds/3-27.mp3",
    "image": "images/27.png",
    "transcript": "男 歡迎光臨!請問要點什麼?\n女 我要兩個漢堡。\n男 還要別的嗎?我們的咖啡很不錯！\n女 好的，請給我一杯熱咖啡。\n男 請問這位小姐點了什麼?",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 28,
    "part": 3,
    "question": "",
    "audio": "sounds/3-28.mp3",
    "image": "images/28.png",
    "transcript": "男 老闆，我可以穿穿看這件衣服嗎?\n女 可以，請到裡面試試。\n男 這件衣服太小了，還有大一點兒的嗎?\n女 對不起，大的已經賣完了。\n男 請問這位先生覺得這件衣服怎麼樣?",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 29,
    "part": 3,
    "question": "",
    "audio": "sounds/3-29.mp3",
    "image": "images/29.png",
    "transcript": "男 王同學，明天上籃球課，你先去借幾顆籃球吧！\n女 老師，同學們比較想去游泳，他們要我問問您。\n男 可是這個星期林老師的學生好像要練習游泳。\n女 老師，我剛剛問林老師了，他說我們可以在星期三和星期五上游泳課，這兩天他們不練習。\n男 請問學生們什麼時候可以上游泳課？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 30,
    "part": 3,
    "question": "",
    "audio": "sounds3-30.mp3",
    "image": "images/30.png",
    "transcript": "男 這是你家全部的人嗎？\n女 是啊，這是爸爸、媽媽、兩個妹妹和我。\n男 妳沒有哥哥或弟弟嗎？\n女 沒有，我們家一共五個人。\n男 請問哪一張是女生家人的照片？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 31,
    "part": 3,
    "question": "",
    "audio": "sounds/3-31.mp3",
    "image": "images/31.png",
    "transcript": "男 各位同學，作業有沒有什麼問題？\n女 老師，作業裡有一個管理報告要寫，可是我們從沒做過這方面的報告。\n男 你們幾個同學一起，先去圖書館找這方面的書，然後跟我一起討論。\n女 好吧！我們試試。\n男 請問老師要同學們做什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 32,
    "part": 3,
    "question": "",
    "audio": "sounds/3-32.mp3",
    "image": "images/32.png",
    "transcript": "男 危險！快點離開大樓。\n女 我住這裡，我要進去。\n男 樓快倒了，很不安全！\n女 我住三樓，東西都在裡面，我要進去。\n男 請問他們現在在哪裡？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 33,
    "part": 3,
    "question": "",
    "audio": "sounds/3-33.mp3",
    "image": "images/33.png",
    "transcript": "男 月華，你把數學作業的答案寫在黑板上吧！\n女 老師，我的作業被王小明拿走了。\n男 喔？沒關係，我把問題寫在黑板上了，你上來回答吧！\n女 唉！老師，我不會寫。\n男 請問老師要月華做什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 34,
    "part": 3,
    "question": "",
    "audio": "sounds/3-34.mp3",
    "image": "images/34.png",
    "transcript": "男 飛機要起飛了，你怎麼還在這裡？\n女 我找不到我的機票。\n男 機票這麼重要的東西，怎麼會不見呢？\n女 唉啊！你快一點幫我找找吧！\n男 請問這位小姐要這位先生找什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 35,
    "part": 3,
    "question": "",
    "audio": "sounds/3-35.mp3",
    "image": "images/35.png",
    "transcript": "男 哇！這個味道好香啊！你在做什麼？\n女 烤牛肉。\n男 桌上這些菜都是你做的嗎？\n女 對啊！今天的晚餐我還準備了湯、水果和酒。\n男 請問他們晚餐吃什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 36,
    "part": 3,
    "question": "",
    "audio": "sounds/3-36.mp3",
    "image": "images/36.png",
    "transcript": "男 這裡的環境好舒服啊！空氣也很好。\n女 對面鄰居種了很多花，所以有時候會有花香。\n男 你以前一直說想學騎腳踏車和開車，你學了嗎？\n女 嗯，這裡什麼都好，就是交通不方便，所以我學了開車。\n男 請問這位小姐來這裡以後，學會了什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 37,
    "part": 3,
    "question": "",
    "audio": "sounds/3-37.mp3",
    "image": "images/37.png",
    "transcript": "男 文文，你是不是感冒了？ 要不要喝一點水？\n女 我沒感冒啊！\n男 那你怎麼一直咳嗽？\n女 我剛剛吃東西吃太快了，等一會兒就好了。\n男 請問文文怎麼了？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 38,
    "part": 3,
    "question": "",
    "audio": "sounds/3-38.mp3",
    "image": "images/38.png",
    "transcript": "男 你這一個學期的成績怎麼樣？\n女 我的英文還可以，可是數學不好。\n男 我也是數學不好。我們要不要在暑假的時候，找老師教我們？\n女 可是我暑假要搭飛機去英國找我朋友。\n男 請問這位小姐暑假的時候想做什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 39,
    "part": 3,
    "question": "",
    "audio": "sounds/3-39.mp3",
    "image": "images/39.png",
    "transcript": "男 下過雨的天空真是乾淨，空氣的味道也很好，我很喜歡。\n女 你也喜歡這樣的天氣啊！\n男 嗯！夏天的時候，如果下午下過雨，晚上就很涼快。\n女 對啊，這個時候，我喜歡和家人在房子外面看看星星、聊聊天。\n男 請問這位小姐喜歡做什麼事？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 40,
    "part": 3,
    "question": "",
    "audio": "sounds/3-40.mp3",
    "image": "images/40.png",
    "transcript": "男 你覺得這間房子怎麼樣？\n女 這間房子有樓梯和電梯，應該不便宜吧！\n男 昨天看的房子，樓梯在房子外面，比這一間便宜 2千元。\n女 好吧！就昨天那一間吧！\n男 請問這位小姐想租哪一間房子？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 41,
    "part": 4,
    "question": "",
    "audio": "sounds/4-41.mp3",
    "transcript": "男：這裡很危險，大家快一點離開。\n女：我們要往哪裡走？我沒注意到安全門的方向。\n男：先往前走，安全門在樓梯旁邊，不要搭電梯。\n女：好，我們大家往前走吧！\n男：請問下面哪一個是對的？",
    "options": ["（A）這位先生找不到安全門", "（B）這位小姐想搭電梯下樓", "（C）這位先生要大家往樓梯那兒走", "（D）這位小姐要這位先生快一點離開"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 42,
    "part": 4,
    "question": "",
    "audio": "sounds/4-42.mp3",
    "transcript": "男：媽媽站在路口和鄰居聊天，都過了半小時了。\n女：因為他們正在比較哪一間大學的學費便宜。\n男：媽媽跟鄰居談這個做什麼？\n女：我明年想讀管理學院，媽媽可能是想先了解吧！\n男：請問他們的媽媽為什麼和鄰居聊天？",
    "options": ["（A）想參加大學考試", "（B）想了解大學的學費", "（C）想知道付學費的方法", "（D）想問問讀大學的方法"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 43,
    "part": 4,
    "question": "",
    "audio": "sounds/4-43.mp3",
    "transcript": "男：「顧客永遠是對的」，這一句話我每天要聽經理講十遍。\n女：所以，你也覺得「顧客永遠是對的」嗎？\n男：怎麼可能？他還常說「沒有討厭的客人，只有最好的服務」。\n女：好棒的經理，下次我就去你那兒吃飯！\n男：請問這位先生的職業是什麼？",
    "options": ["（A）記者", "（B）護士", "（C）教師", "（D）服務生"],
    "answer": "D",
    "remark": ""
  },
  {
    "id": 44,
    "part": 4,
    "question": "",
    "audio": "sounds/4-44.mp3",
    "transcript": "男：為了畢業以後能找到好工作，我現在必須非常努力。\n女：你每天從早上讀到晚上，這樣一直讀書就能找到好工作嗎？\n男：妳一放假就出國玩，妳不了解一份好工作有多重要。\n女：我今年六月畢業以後，就要去美國的博物館上班了。\n男：請問下面哪一個是對的？",
    "options": ["（A）這位小姐準備出國工作", "（B）這位先生已經找到工作", "（C）這位小姐每天都在讀書", "（D）這位先生想快一點畢業"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 45,
    "part": 4,
    "question": "",
    "audio": "sounds/4-45.mp3",
    "transcript": "男：謝謝你，今天的舞會，我玩得很愉快。\n女：太好了，你注意到舞會上那位紅頭髮的女孩子了嗎？\n男：喔，妳說明美啊！雖然我們以前沒見過面，可是我們聊得很開心。\n女：太好了，希望你跟她要了電話號碼。\n男：請問這位先生說了什麼？",
    "options": ["（A）他喜歡和明美聊天兒", "（B）他有明美的電話號碼", "（C）他和明美從小就認識", "（D）他和明美一起去舞會"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 46,
    "part": 4,
    "question": "",
    "audio": "sounds/4-46.mp3",
    "transcript": "男：妳遲到了，晚了1小時20分鐘又38秒。\n女：對不起，路上車子多嘛！\n男：我們約會，妳哪一次準時了？還每次都說一樣的話。\n女：你不覺得是你太早到了嗎？\n男：請問下面哪一個是對的？",
    "options": ["（A）這位先生每次都遲到", "（B）這位先生現在不太高興", "（C）這位先生著急地找這位小姐", "（D）這位先生擔心這位小姐的安全"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 47,
    "part": 4,
    "question": "",
    "audio": "sounds/4-47.mp3",
    "transcript": "男：經理也太不客氣了吧！就我們三個人，要做完全部的事。\n女：你經驗最多，先教我們兩個，然後我們再開始做。\n男：教你們可以，可是我們幾個人怎麼可能處理完全部的事啦！\n女：可以、可以，快點把事情做完，我們就能回家休息了。\n男：請問這位先生覺得經理給的工作怎麼樣？",
    "options": ["（A）他很願意幫忙", "（B）他完全沒經驗", "（C）他需要有人教他", "（D）他認為工作太多"],
    "answer": "D",
    "remark": ""
  },
  {
    "id": 48,
    "part": 4,
    "question": "",
    "audio": "sounds/4-48.mp3",
    "transcript": "男：我最近都睡得不好，剛剛去看病。\n女：醫生說了什麼？\n男：他叫我要常常出去走走、多運動，就可以睡得比較好。\n女：是啊！不過最近天氣冷，很容易感冒，你出門要多穿一件衣服。\n男：這位先生看病的原因是什麼？",
    "options": ["（A）感冒了", "（B）害怕出門", "（C）常常睡不好", "（D）一運動就覺得累"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 49,
    "part": 4,
    "question": "",
    "audio": "sounds/4-49.mp3",
    "transcript": "男：妳停車、停車，怎麼可以一邊開車一邊喝酒？\n女：警察先生，我沒有喝酒，我只是拿著酒，沒有喝。\n男：下車，妳下車，把手放到頭上去。\n女：我一隻手拿著酒、一隻手開車，沒有手可以放到頭上了。\n男：請問警察要這位小姐做什麼？",
    "options": ["（A）把手放車門", "（B）從車上下來", "（C）離開警察局", "（D）把酒拿出來"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 50,
    "part": 4,
    "question": "",
    "audio": "sounds/4-50.mp3",
    "transcript": "男：老王的年紀比他太太大20歲啊！\n女：好像是這樣，可是他們很幸福，年紀不是問題吧！\n男：只要能夠了解自己的太太或是先生，日子就會過得很幸福。\n女：了解自己，相信別人，就是兩個人一起生活最重要的事。\n男：請問他們在討論什麼事？",
    "options": ["（A）幾歲結婚比較好", "（B）結婚要準備哪些東西", "（C）要怎樣才能有幸福的生活", "（D）要怎麼做才能讓人相信自己"],
    "answer": "C",
    "remark": ""
  }
];
